### PR TITLE
"Единообразие" instead of "консистентного"

### PR DESCRIPTION
**Pull request by gvidon**
Russian word "единообразие" is more understandable and more suitable for describing consistency in this context.

### CODE REVIEW

**Comment by vanesyan** [comment]
-1 I'm against of your opinion. Косистентный is better sounded than единообразие in this context.

**Comment by gvidon** [comment]
Yes, I agree it sounds great, it looks great. But "единообразие" is just simpler and _more_russian_ if you wish.

**Comment by vanesyan** [comment]
Единообразный does not always mean консистентный. It's thin verge between there. консистентный means "looks like so, but with some maybe additional, but without breaking existing rules", but eдинообразный take more strict semantic, it's should be the same for 100%.

**Comment by vanesyan** [comment]
Maybe I'm wrong, correct me if so :smiley:

**Comment by gvidon** [comment]
*"Консистентный"* means *"consistent"*. That means *"последовательный"* in russian. *"Последовательный"* means *if A->B, B->C then A->C*, or something like this.

In the same time *"единообразный"* is exactly about similarity, literally it means *"same/similar look (shape/representation)"*.

**Comment by vanesyan** [comment]
translation of "consistent" as "согласующийся" more relevant for this context.

**Comment by vanesyan** [comment]
But "единообразный" has synonyms: "однородный", "одинаковый", "единный", which as I had said before have strict semantic.

**Comment by gvidon** [comment]
I agree. But *"единообразный"* still seems to me a better translation.

**Comment by vanesyan** [comment]
ok, it's your opinion, I've no rights to trying to change it :smiley:

**Comment by ArtemFitiskin** [comment]
Лол)

**Comment by Piterden** [comment]
> translation of "consistent" as "согласующийся" more relevant for this context.

I suppose it would be better to use "согласующийся" instead of "последовательный". The last one causes confuse situations during explanations to a newbie. The phrase "Вы должны быть последовательны" doesn't make him clear what exactly we want from him! I sure that phrases like "Вы должны писать согласующийся код", "Согласования на уровне команды", "Общепринятые согласования" would be much better for understanding by people!

**Comment by Piterden** [comment]
BTW, I think this misunderstanding is caused by a next: _consistent_ (_последовательный_) has a root of _consist_ which means _содержать_. Russian translation has another root _след_ which means _follow_. So in English it would be like _you should follow yourself in your actions_ which means _вы должны быть последовательны_.

**Pull request closed without merging**
